version: '3'

services:
  database:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=CYbnKI0Ll3K0uC2tgv84
      - APP_DB_USER=docker
      - APP_DB_PASS=C4iELjeL8Nc7Kzr17tCw
      - APP_DB_NAME=smartintercom
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  api:
    build: ./smart-intercom-api/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DB_CONNECTION=postgresql://docker:C4iELjeL8Nc7Kzr17tCw@database:5432/smartintercom
      - VAPID_PUBLIC=BJJ2P64jPFBQ8jIc_l4SsHMMwMIzEY_6wMvGMSTnO3_rklTg2XtZM8OC3Sw8MlZ8--NsKXvkOTEQmqbW_rl08zc
      - VAPID_PRIVATE=KQc-F0ZHIvupzVk_lAy6IRv8umTuYofBfMO8WlNCyBA
      - VAPID_SUBJECT=https://protofablab.ch
    depends_on:
      - mqtt
    links:
      - database
    ports:
      - 3000:3000

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./smart-intercom-ui/ui-dist:/usr/share/nginx/html
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - certbot
    links:
      - api
    
  certbot:
    image: certbot/certbot:arm32v6-latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  
  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mqtt/config/:/mosquitto/config/:ro
      - ./mqtt/data/:/mosquitto/data/
    ports:
      - 1883:1883