{
 "title": "ProtoFabStats",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "APDS9960",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"event\" FROM \"APDS9960\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "occupancy",
     "query": "SELECT \"occupancy\" FROM \"APDS9960_processed\"\n\n\n"
    }
   ]
  },
  {
   "title": "APDS9960 - Occupancy last 7 days",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "occupancy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(occupancy) FROM \"APDS9960_processed\" WHERE time > now() - 7d GROUP BY time(1d)  ORDER BY time ASC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "APDS9960 - Days of Week Average",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT average FROM \"APDS9960_days_of_week\" ORDER BY time DESC LIMIT 7 ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "APDS9960 - Hours Average",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT average FROM \"APDS9960_hour\" ORDER BY time DESC\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "User Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT event_type FROM \"user_events_1\" "
    }
   ]
  },
  {
   "title": "VL53L4CX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT * FROM \"VL53L4CX\""
    },
    {
     "query": "SELECT MEDIAN(\"measurement\") FROM \"VL53L4CX\" GROUP BY TIME(500ms) \n"
    },
    {
     "alias": "user_events",
     "query": "SELECT * FROM \"user_events_1\""
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "number_of_users",
     "query": "SELECT number FROM \"number_of_users_1\" "
    }
   ]
  },
  {
   "title": "Door Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locked/Unlocked",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "SELECT status, time FROM \"locked_unlocked\" "
      }
     ]
    },
    {
     "title": "Open/Closed",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "test",
       "query": "SELECT status FROM \"open_closed\" \n"
      }
     ]
    },
    {
     "title": "Door Events",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 12, "x": 6, "y": 42 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT status FROM \"locked_unlocked\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "query": "SELECT status FROM \"open_closed\""
      }
     ]
    }
   ]
  },
  {
   "title": "Draft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  }
 ]
}