version: '3'

services:
  streamlit-app:
    container_name: streamlit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file: ./../.env
    networks:
      - docker-db_unilock-network

networks:
  docker-db_unilock-network:
    external: true
